server:
  port: 1111
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 1998
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
    
eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone : http://localhost:9999/eureka   
    